project:
  type: book

book:
  title: "- R 언어를 이용한 보고서 작성의 기초"
  author: "서울시립대학교 빅데이터혁신융합대학 사업단"
  date: "1/12/2025"
  chapters:
    - intro_R.qmd
    - train_R.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    classoption: oneside
    papersize: A4
# 오류 발생     lang: ko
    fontsize: 11pt
    lof: true
    lot: true
    code-overflow: wrap
    language: custom.yml
    latex-auto-install: true
    latex-tinytex: true
    pdf-engine: xelatex
    crossref:
      fig-title: "그림"
      tbl-title: "표"
      fig-prefix:  "그림" # (default is "Figure")
      tbl-prefix: '' #표    # (default is "Table")
      eq-prefix:  '' #식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    include-in-header: latex/preamble.tex
